SUBJECTS_BY_KEYWORD = {   'abroad': ('EAP', 'STP'),
    'abroads': ('EAP', 'STP'),
    'accountancies': ('ACC',),
    'accountancy': ('ACC',),
    'aero': ('EAE', 'MAE'),
    'aeroes': ('EAE', 'MAE'),
    'aerospace': ('EAE', 'MAE'),
    'aerospaces': ('EAE', 'MAE'),
    'african': ('AAS',),
    'africans': ('AAS',),
    'ag': ('AMR', 'SAF'),
    'agric': ('AMR', 'SAF'),
    'agrics': ('AMR', 'SAF'),
    'agricultural': ('AED', 'IAD', 'AGE', 'AGC', 'ARE', 'ASE'),
    'agriculturals': ('AED', 'IAD', 'AGE', 'AGC', 'ARE', 'ASE'),
    'agriculture': ('AMR', 'SAF'),
    'agricultures': ('AMR', 'SAF'),
    'agronomies': ('AGR',),
    'agronomy': ('AGR',),
    'ags': ('AMR', 'SAF'),
    'allergies': ('RAL',),
    'allergy': ('RAL',),
    'american': ('AAS', 'LAH', 'AMS', 'ASA', 'NAS'),
    'americans': ('AAS', 'LAH', 'AMS', 'ASA', 'NAS'),
    'anat': ('CHA', 'APC'),
    'anatomies': ('CHA', 'APC'),
    'anatomy': ('CHA', 'APC'),
    'anats': ('CHA', 'APC'),
    'anesthesiologies': ('ANE',),
    'anesthesiology': ('ANE',),
    'animal': ('ANG', 'ABG', 'ANS', 'ABI', 'ANB'),
    'animals': ('ANG', 'ABG', 'ANS', 'ABI', 'ANB'),
    'anthropologies': ('ANT',),
    'anthropology': ('ANT',),
    'applied': ('ABT', 'EAL', 'ABS', 'EAD'),
    'applieds': ('ABT', 'EAL', 'ABS', 'EAD'),
    'arabic': ('ARB',),
    'arabics': ('ARB',),
    'architecture': ('LDA',),
    'architectures': ('LDA',),
    'area': ('MGB',),
    'areas': ('MGB',),
    'art': ('ART', 'AHI', 'DRA'),
    'arts': ('ART', 'AHI', 'DRA'),
    'asian': ('EAS', 'ASA', 'MSA'),
    'asians': ('EAS', 'ASA', 'MSA'),
    'assistant': ('PAS',),
    'assistants': ('PAS',),
    'astronomies': ('AST',),
    'astronomy': ('AST',),
    'at': ('CLR',),
    'atmospheric': ('ATM',),
    'atmospherics': ('ATM',),
    'ats': ('CLR',),
    'avian': ('AVS',),
    'avians': ('AVS',),
    'bay': ('MGB',),
    'bays': ('MGB',),
    'behavior': ('NPB', 'ANB'),
    'behavioral': ('ABS',),
    'behaviorals': ('ABS',),
    'behaviors': ('NPB', 'ANB'),
    'bio': (   'BIS',
               'BCM',
               'EXB',
               'GDB',
               'ABT',
               'NUB',
               'PBI',
               'WFC',
               'PBG',
               'CDB',
               'BMB',
               'EBS',
               'CHA',
               'MCB',
               'ABG',
               'PLB',
               'ABI',
               'APC',
               'BCB'),
    'biochemistries': ('BMB',),
    'biochemistry': ('BMB',),
    'biol': (   'BIS',
                'BCM',
                'EXB',
                'GDB',
                'ABT',
                'NUB',
                'PBI',
                'WFC',
                'PBG',
                'CDB',
                'BMB',
                'EBS',
                'CHA',
                'MCB',
                'ABG',
                'PLB',
                'ABI',
                'APC',
                'BCB'),
    'biological': (   'BIS',
                      'BCM',
                      'EXB',
                      'GDB',
                      'ABT',
                      'NUB',
                      'PBI',
                      'WFC',
                      'PBG',
                      'CDB',
                      'BMB',
                      'EBS',
                      'CHA',
                      'MCB',
                      'ABG',
                      'PLB',
                      'ABI',
                      'APC',
                      'BCB'),
    'biologicals': (   'BIS',
                       'BCM',
                       'EXB',
                       'GDB',
                       'ABT',
                       'NUB',
                       'PBI',
                       'WFC',
                       'PBG',
                       'CDB',
                       'BMB',
                       'EBS',
                       'CHA',
                       'MCB',
                       'ABG',
                       'PLB',
                       'ABI',
                       'APC',
                       'BCB'),
    'biologies': (   'BIS',
                     'BCM',
                     'EXB',
                     'GDB',
                     'ABT',
                     'NUB',
                     'PBI',
                     'WFC',
                     'PBG',
                     'CDB',
                     'BMB',
                     'EBS',
                     'CHA',
                     'MCB',
                     'ABG',
                     'PLB',
                     'ABI',
                     'APC',
                     'BCB'),
    'biology': (   'BIS',
                   'BCM',
                   'EXB',
                   'GDB',
                   'ABT',
                   'NUB',
                   'PBI',
                   'WFC',
                   'PBG',
                   'CDB',
                   'BMB',
                   'EBS',
                   'CHA',
                   'MCB',
                   'ABG',
                   'PLB',
                   'ABI',
                   'APC',
                   'BCB'),
    'biols': (   'BIS',
                 'BCM',
                 'EXB',
                 'GDB',
                 'ABT',
                 'NUB',
                 'PBI',
                 'WFC',
                 'PBG',
                 'CDB',
                 'BMB',
                 'EBS',
                 'CHA',
                 'MCB',
                 'ABG',
                 'PLB',
                 'ABI',
                 'APC',
                 'BCB'),
    'biomedical': ('BIM',),
    'biomedicals': ('BIM',),
    'biophotonic': ('BPT',),
    'biophotonics': ('BPT',),
    'biophysic': ('BPH',),
    'biophysics': ('BPH',),
    'bios': (   'BIS',
                'BCM',
                'EXB',
                'GDB',
                'ABT',
                'NUB',
                'PBI',
                'WFC',
                'PBG',
                'CDB',
                'BMB',
                'EBS',
                'CHA',
                'MCB',
                'ABG',
                'PLB',
                'ABI',
                'APC',
                'BCB'),
    'bioscience': ('VMB',),
    'biosciences': ('VMB',),
    'biostatistic': ('BST',),
    'biostatistics': ('BST',),
    'biotechnologies': ('DEB', 'BIT'),
    'biotechnology': ('DEB', 'BIT'),
    'cantonese': ('CAN',),
    'cardiologies': ('CAR',),
    'cardiology': ('CAR',),
    'cell': ('MCP', 'CDB', 'CHA', 'APC', 'BCB'),
    'cells': ('MCP', 'CDB', 'CHA', 'APC', 'BCB'),
    'cellular': ('MCB',),
    'cellulars': ('MCB',),
    'celtic': ('CEL',),
    'celtics': ('CEL',),
    'challenge': ('HNR',),
    'challenges': ('HNR',),
    'chem': ('BCM', 'AGC', 'ECH', 'ECM', 'CHE'),
    'chemical': ('BCM', 'AGC', 'ECH', 'ECM', 'CHE'),
    'chemicals': ('BCM', 'AGC', 'ECH', 'ECM', 'CHE'),
    'chemistries': ('BCM', 'AGC', 'ECH', 'ECM', 'CHE'),
    'chemistry': ('BCM', 'AGC', 'ECH', 'ECM', 'CHE'),
    'chems': ('BCM', 'AGC', 'ECH', 'ECM', 'CHE'),
    'chicana': ('CHI',),
    'chicana/o': ('CHI',),
    'chicana/oes': ('CHI',),
    'chicanas': ('CHI',),
    'chicano': ('CHI',),
    'chicanoes': ('CHI',),
    'chinese': ('CHN',),
    'cinema': ('CDM', 'CTS'),
    'cinemas': ('CDM', 'CTS'),
    'civil': ('ECI',),
    'civils': ('ECI',),
    'classic': ('CLA',),
    'classics': ('CLA',),
    'clinic': ('DVM', 'CPS', 'CLH', 'NCM'),
    'clinical': ('DVM', 'CPS', 'CLH', 'NCM'),
    'clinicals': ('DVM', 'CPS', 'CLH', 'NCM'),
    'clinics': ('DVM', 'CPS', 'CLH', 'NCM'),
    'clothing': ('TXC',),
    'clothings': ('TXC',),
    'cognitive': ('CGS',),
    'cognitives': ('CGS',),
    'college': ('CLR',),
    'colleges': ('CLR',),
    'commercial': ('ICL',),
    'commercials': ('ICL',),
    'communication': ('CMN',),
    'communications': ('CMN',),
    'communities': ('CRD', 'CMH'),
    'community': ('CRD', 'CMH'),
    'comp': ('ECS', 'EEC'),
    'compar': ('STH', 'COM'),
    'comparative': ('STH', 'COM'),
    'comparatives': ('STH', 'COM'),
    'compars': ('STH', 'COM'),
    'comps': ('ECS', 'EEC'),
    'compu': ('ECS', 'EEC'),
    'compus': ('ECS', 'EEC'),
    'computer': ('ECS', 'EEC'),
    'computers': ('ECS', 'EEC'),
    'conserv': ('WFC',),
    'conservation': ('WFC',),
    'conservations': ('WFC',),
    'conservs': ('WFC',),
    'consumer': ('CNS', 'CNE'),
    'consumers': ('CNS', 'CNE'),
    'critical': ('CRI',),
    'criticals': ('CRI',),
    'croatian': ('CRO',),
    'croatians': ('CRO',),
    'crop': ('CSM', 'VCR'),
    'crops': ('CSM', 'VCR'),
    'cultural': ('CST',),
    'culturals': ('CST',),
    'culture': ('NAC',),
    'cultures': ('NAC',),
    'danish': ('DAN',),
    'danishes': ('DAN',),
    'davi': ('EAD',),
    'davis': ('EAD',),
    'dermatologies': ('DER',),
    'dermatology': ('DER',),
    'desig': ('DEB', 'DES', 'CRI'),
    'design': ('DEB', 'DES', 'CRI'),
    'designs': ('DEB', 'DES', 'CRI'),
    'desigs': ('DEB', 'DES', 'CRI'),
    'dev': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'development': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'developmental': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'developmentals': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'developments': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'develpmnt': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'develpmnts': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'devs': ('IAD', 'HDE', 'CDB', 'CRD', 'BCB'),
    'di': ('IDI',),
    'diagnostic': ('RDI',),
    'diagnostics': ('RDI',),
    'digital': ('CDM',),
    'digitals': ('CDM',),
    'dis': ('IDI',),
    'disease': ('GDB', 'IDI'),
    'diseases': ('GDB', 'IDI'),
    'dramatic': ('DRA',),
    'dramatics': ('DRA',),
    'east': ('EAS', 'MSA'),
    'easts': ('EAS', 'MSA'),
    'ecologies': ('EVE', 'ECL'),
    'ecology': ('EVE', 'ECL'),
    'econ': ('AGE', 'CNE', 'ECN', 'ARE'),
    'economic': ('AGE', 'CNE', 'ECN', 'ARE'),
    'economics': ('AGE', 'CNE', 'ECN', 'ARE'),
    'economies': ('EJS',),
    'economy': ('EJS',),
    'econs': ('AGE', 'CNE', 'ECN', 'ARE'),
    'education': ('AED', 'EDU', 'PHE', 'EAP'),
    'educations': ('AED', 'EDU', 'PHE', 'EAP'),
    'electrical': ('EEC',),
    'electricals': ('EEC',),
    'emergencies': ('EMR',),
    'emergency': ('EMR',),
    'empha': ('DEB', 'CRI'),
    'emphas': ('DEB', 'CRI'),
    'emphases': ('DEB', 'CRI'),
    'emphasis': ('DEB', 'CRI'),
    'endocrinol': ('EDO', 'ENM'),
    'endocrinologies': ('EDO', 'ENM'),
    'endocrinology': ('EDO', 'ENM'),
    'endocrinols': ('EDO', 'ENM'),
    'engineer': (   'EME',
                    'BIM',
                    'ECS',
                    'EAL',
                    'EAE',
                    'EBS',
                    'MAE',
                    'ECI',
                    'ECH',
                    'ECM',
                    'ENG',
                    'EAD',
                    'EEC',
                    'EMS'),
    'engineering': (   'EME',
                       'BIM',
                       'ECS',
                       'EAL',
                       'EAE',
                       'EBS',
                       'MAE',
                       'ECI',
                       'ECH',
                       'ECM',
                       'ENG',
                       'EAD',
                       'EEC',
                       'EMS'),
    'engineerings': (   'EME',
                        'BIM',
                        'ECS',
                        'EAL',
                        'EAE',
                        'EBS',
                        'MAE',
                        'ECI',
                        'ECH',
                        'ECM',
                        'ENG',
                        'EAD',
                        'EEC',
                        'EMS'),
    'engineers': (   'EME',
                     'BIM',
                     'ECS',
                     'EAL',
                     'EAE',
                     'EBS',
                     'MAE',
                     'ECI',
                     'ECH',
                     'ECM',
                     'ENG',
                     'EAD',
                     'EEC',
                     'EMS'),
    'english': ('ENL',),
    'englishes': ('ENL',),
    'enologies': ('VEN',),
    'enology': ('VEN',),
    'entomologies': ('ENT',),
    'entomology': ('ENT',),
    'envir': (   'ERS',
                 'ETX',
                 'ENH',
                 'ESM',
                 'AGC',
                 'ESP',
                 'ECI',
                 'EST',
                 'ASE',
                 'ENP',
                 'OEH'),
    'environ': (   'ERS',
                   'ETX',
                   'ENH',
                   'ESM',
                   'AGC',
                   'ESP',
                   'ECI',
                   'EST',
                   'ASE',
                   'ENP',
                   'OEH'),
    'environmental': (   'ERS',
                         'ETX',
                         'ENH',
                         'ESM',
                         'AGC',
                         'ESP',
                         'ECI',
                         'EST',
                         'ASE',
                         'ENP',
                         'OEH'),
    'environmentals': (   'ERS',
                          'ETX',
                          'ENH',
                          'ESM',
                          'AGC',
                          'ESP',
                          'ECI',
                          'EST',
                          'ASE',
                          'ENP',
                          'OEH'),
    'environs': (   'ERS',
                    'ETX',
                    'ENH',
                    'ESM',
                    'AGC',
                    'ESP',
                    'ECI',
                    'EST',
                    'ASE',
                    'ENP',
                    'OEH'),
    'envirs': (   'ERS',
                  'ETX',
                  'ENH',
                  'ESM',
                  'AGC',
                  'ESP',
                  'ECI',
                  'EST',
                  'ASE',
                  'ENP',
                  'OEH'),
    'envrn': (   'ERS',
                 'ETX',
                 'ENH',
                 'ESM',
                 'AGC',
                 'ESP',
                 'ECI',
                 'EST',
                 'ASE',
                 'ENP',
                 'OEH'),
    'envrns': (   'ERS',
                  'ETX',
                  'ENH',
                  'ESM',
                  'AGC',
                  'ESP',
                  'ECI',
                  'EST',
                  'ASE',
                  'ENP',
                  'OEH'),
    'epidemiologies': ('EPI', 'EPP', 'VME'),
    'epidemiology': ('EPI', 'EPP', 'VME'),
    'evolution': ('EVE',),
    'evolutions': ('EVE',),
    'exercise': ('EXB', 'EXS'),
    'exercises': ('EXB', 'EXS'),
    'families': ('FAP',),
    'family': ('FAP',),
    'fiber': ('FPS',),
    'fibers': ('FPS',),
    'film': ('FMS',),
    'films': ('FMS',),
    'fish': ('WFC',),
    'food': ('FSM', 'SAF', 'FST'),
    'foods': ('FSM', 'SAF', 'FST'),
    'forensic': ('FOR',),
    'forensics': ('FOR',),
    'french': ('FRE',),
    'frenches': ('FRE',),
    'freshman': ('FRS',),
    'freshmen': ('FRS',),
    'gastroenterologies': ('GAS',),
    'gastroenterology': ('GAS',),
    'general': ('GMD',),
    'generals': ('GMD',),
    'genetic': ('GGG', 'ANG'),
    'genetics': ('GGG', 'ANG'),
    'geographies': ('GEO',),
    'geography': ('GEO',),
    'geologies': ('GEL',),
    'geology': ('GEL',),
    'german': ('GER',),
    'germen': ('GER',),
    'gg': ('BCB',),
    'ggs': ('BCB',),
    'global': ('GDB',),
    'globals': ('GDB',),
    'gp': ('ABG', 'ANB'),
    'gps': ('ABG', 'ANB'),
    'grad': (   'EDO',
                'GGG',
                'EPI',
                'PFS',
                'NSC',
                'NUB',
                'PBI',
                'IMM',
                'CDB',
                'BMB',
                'AGC',
                'PGG',
                'ABG',
                'NGG',
                'BPH',
                'ANB',
                'PTX',
                'MIB'),
    'grads': (   'EDO',
                 'GGG',
                 'EPI',
                 'PFS',
                 'NSC',
                 'NUB',
                 'PBI',
                 'IMM',
                 'CDB',
                 'BMB',
                 'AGC',
                 'PGG',
                 'ABG',
                 'NGG',
                 'BPH',
                 'ANB',
                 'PTX',
                 'MIB'),
    'graduate': (   'EDO',
                    'GGG',
                    'EPI',
                    'PFS',
                    'NSC',
                    'NUB',
                    'PBI',
                    'IMM',
                    'CDB',
                    'BMB',
                    'AGC',
                    'PGG',
                    'ABG',
                    'NGG',
                    'BPH',
                    'ANB',
                    'PTX',
                    'MIB'),
    'graduates': (   'EDO',
                     'GGG',
                     'EPI',
                     'PFS',
                     'NSC',
                     'NUB',
                     'PBI',
                     'IMM',
                     'CDB',
                     'BMB',
                     'AGC',
                     'PGG',
                     'ABG',
                     'NGG',
                     'BPH',
                     'ANB',
                     'PTX',
                     'MIB'),
    'greek': ('GRK',),
    'greeks': ('GRK',),
    'group': (   'EDO',
                 'GGG',
                 'EPI',
                 'PFS',
                 'NSC',
                 'NUB',
                 'PBI',
                 'IMM',
                 'PGG',
                 'NGG',
                 'BPH',
                 'MIB'),
    'groups': (   'EDO',
                  'GGG',
                  'EPI',
                  'PFS',
                  'NSC',
                  'NUB',
                  'PBI',
                  'IMM',
                  'PGG',
                  'NGG',
                  'BPH',
                  'MIB'),
    'grp': (   'EDO',
               'GGG',
               'EPI',
               'PFS',
               'NSC',
               'NUB',
               'PBI',
               'IMM',
               'PGG',
               'NGG',
               'BPH',
               'MIB'),
    'grps': (   'EDO',
                'GGG',
                'EPI',
                'PFS',
                'NSC',
                'NUB',
                'PBI',
                'IMM',
                'PGG',
                'NGG',
                'BPH',
                'MIB'),
    'gynecologies': ('OBG',),
    'gynecology': ('OBG',),
    'health': ('SPH', 'MPH', 'CMH', 'PHR', 'MHI', 'OEH'),
    'healths': ('SPH', 'MPH', 'CMH', 'PHR', 'MHI', 'OEH'),
    'hebrew': ('HEB',),
    'hebrews': ('HEB',),
    'hematologies': ('HON',),
    'hematology': ('HON',),
    'hemispheric': ('LAH',),
    'hemispherics': ('LAH',),
    'hindi': ('HIN',),
    'hindis': ('HIN',),
    'histories': ('HIS', 'STH', 'AHI', 'HPS'),
    'history': ('HIS', 'STH', 'AHI', 'HPS'),
    'hlth': ('SPH', 'MPH', 'CMH', 'PHR', 'MHI', 'OEH'),
    'hlths': ('SPH', 'MPH', 'CMH', 'PHR', 'MHI', 'OEH'),
    'honor': ('HNR',),
    'honors': ('HNR',),
    'horticulture': ('ENH', 'HRT'),
    'horticultures': ('ENH', 'HRT'),
    'human': ('HDE', 'HMR', 'CHA', 'HPH'),
    'humanities': ('HUM',),
    'humanity': ('HUM',),
    'humans': ('HDE', 'HMR', 'CHA', 'HPH'),
    'hungarian': ('HUN',),
    'hungarians': ('HUN',),
    'hydrologic': ('HYD',),
    'hydrologics': ('HYD',),
    'immun': ('IMM', 'PMI'),
    'immunologies': ('IMM', 'PMI'),
    'immunology': ('IMM', 'PMI'),
    'immuns': ('IMM', 'PMI'),
    'infectious': ('IDI',),
    'infectiouses': ('IDI',),
    'informatic': ('MDI', 'MHI'),
    'informatics': ('MDI', 'MHI'),
    'int': (   'MCP',
               'CAR',
               'ENM',
               'EMR',
               'IMD',
               'IDI',
               'CMH',
               'HON',
               'NEP',
               'GMD',
               'GAS',
               'PUL',
               'NCM'),
    'integrated': ('IPM', 'IST'),
    'integrateds': ('IPM', 'IST'),
    'internal': (   'MCP',
                    'CAR',
                    'ENM',
                    'EMR',
                    'IMD',
                    'IDI',
                    'CMH',
                    'HON',
                    'NEP',
                    'GMD',
                    'GAS',
                    'PUL',
                    'NCM'),
    'internals': (   'MCP',
                     'CAR',
                     'ENM',
                     'EMR',
                     'IMD',
                     'IDI',
                     'CMH',
                     'HON',
                     'NEP',
                     'GMD',
                     'GAS',
                     'PUL',
                     'NCM'),
    'international': ('IAD', 'ICL', 'IRE'),
    'internationals': ('IAD', 'ICL', 'IRE'),
    'intl': (   'MCP',
                'CAR',
                'ENM',
                'EMR',
                'IMD',
                'IDI',
                'CMH',
                'HON',
                'NEP',
                'GMD',
                'GAS',
                'PUL',
                'NCM'),
    'intls': (   'MCP',
                 'CAR',
                 'ENM',
                 'EMR',
                 'IMD',
                 'IDI',
                 'CMH',
                 'HON',
                 'NEP',
                 'GMD',
                 'GAS',
                 'PUL',
                 'NCM'),
    'intrl': (   'MCP',
                 'CAR',
                 'ENM',
                 'EMR',
                 'IMD',
                 'IDI',
                 'CMH',
                 'HON',
                 'NEP',
                 'GMD',
                 'GAS',
                 'PUL',
                 'NCM'),
    'intrls': (   'MCP',
                  'CAR',
                  'ENM',
                  'EMR',
                  'IMD',
                  'IDI',
                  'CMH',
                  'HON',
                  'NEP',
                  'GMD',
                  'GAS',
                  'PUL',
                  'NCM'),
    'ints': (   'MCP',
                'CAR',
                'ENM',
                'EMR',
                'IMD',
                'IDI',
                'CMH',
                'HON',
                'NEP',
                'GMD',
                'GAS',
                'PUL',
                'NCM'),
    'italian': ('ITA',),
    'italians': ('ITA',),
    'japanese': ('JPN',),
    'jewish': ('JST',),
    'jewishes': ('JST',),
    'justice': ('EJS',),
    'justices': ('EJS',),
    'la': ('CLR',),
    'landscape': ('LDA',),
    'landscapes': ('LDA',),
    'las': ('CLR',),
    'latin': ('LAH', 'LAT'),
    'latins': ('LAH', 'LAT'),
    'law': ('LAW', 'ICL'),
    'laws': ('LAW', 'ICL'),
    'linguistic': ('LIN',),
    'linguistics': ('LIN',),
    'literature': ('COM',),
    'literatures': ('COM',),
    'livermore': ('EAL',),
    'livermores': ('EAL',),
    'lvrmor': ('EAL',),
    'lvrmors': ('EAL',),
    'management': (   'MGP',
                      'ESM',
                      'MGT',
                      'IPM',
                      'FSM',
                      'CSM',
                      'AMR',
                      'MGB',
                      'ENP',
                      'PPP'),
    'managements': (   'MGP',
                       'ESM',
                       'MGT',
                       'IPM',
                       'FSM',
                       'CSM',
                       'AMR',
                       'MGB',
                       'ENP',
                       'PPP'),
    'managemnt': (   'MGP',
                     'ESM',
                     'MGT',
                     'IPM',
                     'FSM',
                     'CSM',
                     'AMR',
                     'MGB',
                     'ENP',
                     'PPP'),
    'managemnts': (   'MGP',
                      'ESM',
                      'MGT',
                      'IPM',
                      'FSM',
                      'CSM',
                      'AMR',
                      'MGB',
                      'ENP',
                      'PPP'),
    'mangmt': (   'MGP',
                  'ESM',
                  'MGT',
                  'IPM',
                  'FSM',
                  'CSM',
                  'AMR',
                  'MGB',
                  'ENP',
                  'PPP'),
    'mangmts': (   'MGP',
                   'ESM',
                   'MGT',
                   'IPM',
                   'FSM',
                   'CSM',
                   'AMR',
                   'MGB',
                   'ENP',
                   'PPP'),
    'master': ('MPH',),
    'masters': ('MPH',),
    'material': ('ECM', 'EMS'),
    'materials': ('ECM', 'EMS'),
    'math': ('MPS', 'MAT'),
    'mathematic': ('MPS', 'MAT'),
    'mathematics': ('MPS', 'MAT'),
    'maths': ('MPS', 'MAT'),
    'mechanical': ('EME', 'MAE'),
    'mechanicals': ('EME', 'MAE'),
    'med': (   'OPT',
               'RAL',
               'RDI',
               'URO',
               'EPP',
               'BCM',
               'MDS',
               'CAR',
               'PMD',
               'SPH',
               'FAP',
               'MPM',
               'VET',
               'SUR',
               'VMD',
               'OTO',
               'OSU',
               'CPS',
               'PED',
               'PHA',
               'CHA',
               'ENM',
               'DER',
               'VME',
               'EMR',
               'IMD',
               'HPH',
               'OBG',
               'ANE',
               'PMR',
               'NSU',
               'IDI',
               'CMH',
               'HON',
               'RNU',
               'NEP',
               'GMD',
               'GAS',
               'RON',
               'MMI',
               'PUL',
               'PSU',
               'OEH',
               'NCM',
               'PSY',
               'NEU'),
    'media': ('CDM',),
    'medias': ('CDM',),
    'medical': ('MDS', 'PHA', 'MDI', 'MMI'),
    'medicals': ('MDS', 'PHA', 'MDI', 'MMI'),
    'medicine': (   'OPT',
                    'RAL',
                    'RDI',
                    'URO',
                    'EPP',
                    'BCM',
                    'MDS',
                    'CAR',
                    'PMD',
                    'SPH',
                    'FAP',
                    'MPM',
                    'VET',
                    'SUR',
                    'VMD',
                    'OTO',
                    'OSU',
                    'CPS',
                    'PED',
                    'PHA',
                    'CHA',
                    'ENM',
                    'DER',
                    'VME',
                    'EMR',
                    'IMD',
                    'HPH',
                    'OBG',
                    'ANE',
                    'PMR',
                    'NSU',
                    'IDI',
                    'CMH',
                    'HON',
                    'RNU',
                    'NEP',
                    'GMD',
                    'GAS',
                    'RON',
                    'MMI',
                    'PUL',
                    'PSU',
                    'OEH',
                    'NCM',
                    'PSY',
                    'NEU'),
    'medicines': (   'OPT',
                     'RAL',
                     'RDI',
                     'URO',
                     'EPP',
                     'BCM',
                     'MDS',
                     'CAR',
                     'PMD',
                     'SPH',
                     'FAP',
                     'MPM',
                     'VET',
                     'SUR',
                     'VMD',
                     'OTO',
                     'OSU',
                     'CPS',
                     'PED',
                     'PHA',
                     'CHA',
                     'ENM',
                     'DER',
                     'VME',
                     'EMR',
                     'IMD',
                     'HPH',
                     'OBG',
                     'ANE',
                     'PMR',
                     'NSU',
                     'IDI',
                     'CMH',
                     'HON',
                     'RNU',
                     'NEP',
                     'GMD',
                     'GAS',
                     'RON',
                     'MMI',
                     'PUL',
                     'PSU',
                     'OEH',
                     'NCM',
                     'PSY',
                     'NEU'),
    'medieval': ('MST',),
    'medievals': ('MST',),
    'meds': (   'OPT',
                'RAL',
                'RDI',
                'URO',
                'EPP',
                'BCM',
                'MDS',
                'CAR',
                'PMD',
                'SPH',
                'FAP',
                'MPM',
                'VET',
                'SUR',
                'VMD',
                'OTO',
                'OSU',
                'CPS',
                'PED',
                'PHA',
                'CHA',
                'ENM',
                'DER',
                'VME',
                'EMR',
                'IMD',
                'HPH',
                'OBG',
                'ANE',
                'PMR',
                'NSU',
                'IDI',
                'CMH',
                'HON',
                'RNU',
                'NEP',
                'GMD',
                'GAS',
                'RON',
                'MMI',
                'PUL',
                'PSU',
                'OEH',
                'NCM',
                'PSY',
                'NEU'),
    'metab': ('ENM', 'NCM'),
    'metabolism': ('ENM', 'NCM'),
    'metabolisms': ('ENM', 'NCM'),
    'metabs': ('ENM', 'NCM'),
    'microbiol': ('PMI', 'MMI', 'MIB', 'MIC'),
    'microbiologies': ('PMI', 'MMI', 'MIB', 'MIC'),
    'microbiology': ('PMI', 'MMI', 'MIB', 'MIC'),
    'microbiols': ('PMI', 'MMI', 'MIB', 'MIC'),
    'middle': ('MSA',),
    'middles': ('MSA',),
    'militaries': ('MSC',),
    'military': ('MSC',),
    'mngt': (   'MGP',
                'ESM',
                'MGT',
                'IPM',
                'FSM',
                'CSM',
                'AMR',
                'MGB',
                'ENP',
                'PPP'),
    'mngts': (   'MGP',
                 'ESM',
                 'MGT',
                 'IPM',
                 'FSM',
                 'CSM',
                 'AMR',
                 'MGB',
                 'ENP',
                 'PPP'),
    'molec': ('MCP', 'VMB', 'BMB', 'MCB', 'BCB'),
    'molecs': ('MCP', 'VMB', 'BMB', 'MCB', 'BCB'),
    'molecular': ('MCP', 'VMB', 'BMB', 'MCB', 'BCB'),
    'moleculars': ('MCP', 'VMB', 'BMB', 'MCB', 'BCB'),
    'music': ('MUS',),
    'musics': ('MUS',),
    'native': ('NAS',),
    'natives': ('NAS',),
    'nature': ('NAC',),
    'natures': ('NAC',),
    'nematologies': ('NEM',),
    'nematology': ('NEM',),
    'nephrologies': ('NEP',),
    'nephrology': ('NEP',),
    'neurobiologies': ('NPB', 'NEU'),
    'neurobiology': ('NPB', 'NEU'),
    'neurologies': ('NPB', 'NEU'),
    'neurology': ('NPB', 'NEU'),
    'neuroscience': ('NSC',),
    'neurosciences': ('NSC',),
    'neurosurgeries': ('NSU',),
    'neurosurgery': ('NSU',),
    'nuclear': ('RNU',),
    'nuclears': ('RNU',),
    'nursing': ('NRS',),
    'nursings': ('NRS',),
    'nutr': ('NUT', 'NGG', 'NCM'),
    'nutrition': ('NUT', 'NGG', 'NCM'),
    'nutritional': ('NUB',),
    'nutritionals': ('NUB',),
    'nutritions': ('NUT', 'NGG', 'NCM'),
    'nutrs': ('NUT', 'NGG', 'NCM'),
    'obstetric': ('OBG',),
    'obstetrics': ('OBG',),
    'occupational': ('OEH',),
    'occupationals': ('OEH',),
    'of': ('REL', 'VET', 'MPH', 'HPS'),
    'ofs': ('REL', 'VET', 'MPH', 'HPS'),
    'oncol': ('HON', 'RON'),
    'oncologies': ('HON', 'RON'),
    'oncology': ('HON', 'RON'),
    'oncols': ('HON', 'RON'),
    'ophthalmologies': ('OPT',),
    'ophthalmology': ('OPT',),
    'orthopaedic': ('OSU',),
    'orthopaedics': ('OSU',),
    'otolaryngologies': ('OTO',),
    'otolaryngology': ('OTO',),
    'pathologies': ('PMD', 'PMI', 'PLP'),
    'pathology': ('PMD', 'PMI', 'PLP'),
    'pediatric': ('PED',),
    'pediatrics': ('PED',),
    'performance': ('PFS',),
    'performances': ('PFS',),
    'pest': ('IPM', 'PPP'),
    'pests': ('IPM', 'PPP'),
    'pharmacol': ('PHA', 'PTX'),
    'pharmacologies': ('PHA', 'PTX'),
    'pharmacology': ('PHA', 'PTX'),
    'pharmacols': ('PHA', 'PTX'),
    'philosophies': ('PHI', 'HPS'),
    'philosophy': ('PHI', 'HPS'),
    'physic': ('PHY',),
    'physical': ('PHE', 'PMR', 'MPS'),
    'physicals': ('PHE', 'PMR', 'MPS'),
    'physician': ('PAS',),
    'physicians': ('PAS',),
    'physics': ('PHY',),
    'physio': ('MCP', 'PGG', 'HPH', 'APC', 'NPB'),
    'physiol': ('MCP', 'PGG', 'HPH', 'APC', 'NPB'),
    'physiologies': ('MCP', 'PGG', 'HPH', 'APC', 'NPB'),
    'physiology': ('MCP', 'PGG', 'HPH', 'APC', 'NPB'),
    'physiols': ('MCP', 'PGG', 'HPH', 'APC', 'NPB'),
    'physios': ('MCP', 'PGG', 'HPH', 'APC', 'NPB'),
    'plan': ('ENP',),
    'plans': ('ENP',),
    'plant': ('PBI', 'PLS', 'PLP', 'PLB', 'PPP'),
    'plants': ('PBI', 'PLS', 'PLP', 'PLB', 'PPP'),
    'plastic': ('PSU',),
    'plastics': ('PSU',),
    'poli': ('POL',),
    'policies': ('ESP', 'TTP'),
    'policy': ('ESP', 'TTP'),
    'polis': ('POL',),
    'political': ('POL',),
    'politicals': ('POL',),
    'polymer': ('FPS',),
    'polymers': ('FPS',),
    'pomologies': ('POM',),
    'pomology': ('POM',),
    'population': ('PBG', 'PHR'),
    'populations': ('PBG', 'PHR'),
    'portuguese': ('POR',),
    'portugueses': ('POR',),
    'practice': ('FAP',),
    'practices': ('FAP',),
    'prev': ('EPP',),
    'preventative': ('EPP',),
    'preventatives': ('EPP',),
    'preventive': ('MPM',),
    'preventives': ('MPM',),
    'prevs': ('EPP',),
    'prof': ('ACC', 'MGB'),
    'professional': ('ACC', 'MGB'),
    'professionals': ('ACC', 'MGB'),
    'professionl': ('MGP',),
    'professionls': ('MGP',),
    'profs': ('ACC', 'MGB'),
    'program': ('UWP', 'EAP', 'STP'),
    'programs': ('UWP', 'EAP', 'STP'),
    'protection': ('PPP',),
    'protections': ('PPP',),
    'psychiatries': ('PSY',),
    'psychiatry': ('PSY',),
    'psychologies': ('PSC', 'CPS'),
    'psychology': ('PSC', 'CPS'),
    'public': ('SPH', 'MPH'),
    'publics': ('SPH', 'MPH'),
    'pulmonaries': ('PUL',),
    'pulmonary': ('PUL',),
    'radiation': ('RON',),
    'radiations': ('RON',),
    'radiological': ('VSR',),
    'radiologicals': ('VSR',),
    'radiologies': ('RDI', 'RNU'),
    'radiology': ('RDI', 'RNU'),
    'range': ('RMT', 'AMR'),
    'ranges': ('RMT', 'AMR'),
    'regional': ('CRD',),
    'regionals': ('CRD',),
    'rehab': ('PMR',),
    'rehabilitation': ('PMR',),
    'rehabilitations': ('PMR',),
    'rehabs': ('PMR',),
    'relation': ('IRE',),
    'relations': ('IRE',),
    'religion': ('REL',),
    'religions': ('REL',),
    'religious': ('RST',),
    'religiouses': ('RST',),
    'reprod': ('PHR',),
    'reprods': ('PHR',),
    'reproductive': ('PHR',),
    'reproductives': ('PHR',),
    'research': ('CLH',),
    'researches': ('CLH',),
    'resource': ('ERS', 'AMR', 'ARE'),
    'resources': ('ERS', 'AMR', 'ARE'),
    'rheumatologies': ('RAL',),
    'rheumatology': ('RAL',),
    'right': ('HMR',),
    'rights': ('HMR',),
    'rotation': ('DVM',),
    'rotations': ('DVM',),
    'rue': ('CLR',),
    'rues': ('CLR',),
    'russian': ('RUS',),
    'russians': ('RUS',),
    'school': ('VET',),
    'schools': ('VET',),
    'sci': (   'ERS',
               'MDS',
               'ECS',
               'EXS',
               'EAL',
               'VSR',
               'CGS',
               'ESM',
               'MSC',
               'EAE',
               'ESP',
               'FPS',
               'CSM',
               'ATM',
               'RMT',
               'FOR',
               'PLS',
               'FST',
               'ANS',
               'SSC',
               'MPS',
               'SAS',
               'EAD',
               'HPS',
               'STS',
               'HYD',
               'EMS',
               'POL'),
    'science': (   'BIS',
                   'ERS',
                   'MDS',
                   'ECS',
                   'EXS',
                   'SPH',
                   'EAL',
                   'CNS',
                   'VSR',
                   'AVS',
                   'CGS',
                   'ESM',
                   'MSC',
                   'EAE',
                   'ESP',
                   'ABS',
                   'FPS',
                   'CSM',
                   'ATM',
                   'RMT',
                   'FOR',
                   'PLS',
                   'FST',
                   'ANS',
                   'SSC',
                   'MPS',
                   'SAS',
                   'EAD',
                   'HPS',
                   'STS',
                   'HYD',
                   'EMS',
                   'POL'),
    'sciences': (   'BIS',
                    'ERS',
                    'MDS',
                    'ECS',
                    'EXS',
                    'SPH',
                    'EAL',
                    'CNS',
                    'VSR',
                    'AVS',
                    'CGS',
                    'ESM',
                    'MSC',
                    'EAE',
                    'ESP',
                    'ABS',
                    'FPS',
                    'CSM',
                    'ATM',
                    'RMT',
                    'FOR',
                    'PLS',
                    'FST',
                    'ANS',
                    'SSC',
                    'MPS',
                    'SAS',
                    'EAD',
                    'HPS',
                    'STS',
                    'HYD',
                    'EMS',
                    'POL'),
    'scis': (   'ERS',
                'MDS',
                'ECS',
                'EXS',
                'EAL',
                'VSR',
                'CGS',
                'ESM',
                'MSC',
                'EAE',
                'ESP',
                'FPS',
                'CSM',
                'ATM',
                'RMT',
                'FOR',
                'PLS',
                'FST',
                'ANS',
                'SSC',
                'MPS',
                'SAS',
                'EAD',
                'HPS',
                'STS',
                'HYD',
                'EMS',
                'POL'),
    'seminar': ('FRS',),
    'seminars': ('FRS',),
    'service': ('FSM',),
    'services': ('FSM',),
    'short': ('STP',),
    'shorts': ('STP',),
    'social': ('STH',),
    'socials': ('STH',),
    'societies': ('EJS', 'SAS'),
    'society': ('EJS', 'SAS'),
    'sociologies': ('SOC',),
    'sociology': ('SOC',),
    'soil': ('SSC',),
    'soils': ('SSC',),
    'south': ('MSA',),
    'souths': ('MSA',),
    'spanish': ('SPA',),
    'spanishes': ('SPA',),
    'statistic': ('STA',),
    'statistics': ('STA',),
    'std': (   'PFS',
               'CST',
               'EAS',
               'CHI',
               'AAS',
               'WMS',
               'AMS',
               'RST',
               'ASA',
               'EST',
               'CTS',
               'PAS',
               'JST',
               'MST',
               'TCS',
               'STS',
               'IST',
               'NAS',
               'MSA',
               'FMS'),
    'stds': (   'PFS',
                'CST',
                'EAS',
                'CHI',
                'AAS',
                'WMS',
                'AMS',
                'RST',
                'ASA',
                'EST',
                'CTS',
                'PAS',
                'JST',
                'MST',
                'TCS',
                'STS',
                'IST',
                'NAS',
                'MSA',
                'FMS'),
    'stud': (   'PFS',
                'CST',
                'EAS',
                'CHI',
                'AAS',
                'WMS',
                'AMS',
                'RST',
                'ASA',
                'EST',
                'CTS',
                'PAS',
                'JST',
                'MST',
                'TCS',
                'STS',
                'IST',
                'NAS',
                'MSA',
                'FMS'),
    'studies': (   'REL',
                   'PFS',
                   'CST',
                   'EAS',
                   'CHI',
                   'AAS',
                   'WMS',
                   'AMS',
                   'RST',
                   'ASA',
                   'EST',
                   'CTS',
                   'PAS',
                   'JST',
                   'MST',
                   'TCS',
                   'STS',
                   'IST',
                   'NAS',
                   'MSA',
                   'FMS'),
    'studio': ('ART',),
    'studios': ('ART',),
    'studs': (   'PFS',
                 'CST',
                 'EAS',
                 'CHI',
                 'AAS',
                 'WMS',
                 'AMS',
                 'RST',
                 'ASA',
                 'EST',
                 'CTS',
                 'PAS',
                 'JST',
                 'MST',
                 'TCS',
                 'STS',
                 'IST',
                 'NAS',
                 'MSA',
                 'FMS'),
    'study': (   'REL',
                 'PFS',
                 'CST',
                 'EAS',
                 'CHI',
                 'AAS',
                 'WMS',
                 'AMS',
                 'RST',
                 'ASA',
                 'EST',
                 'CTS',
                 'PAS',
                 'JST',
                 'MST',
                 'TCS',
                 'STS',
                 'IST',
                 'NAS',
                 'MSA',
                 'FMS'),
    'surgeries': ('SUR', 'OSU', 'PSU'),
    'surgery': ('SUR', 'OSU', 'PSU'),
    'surgical': ('VSR',),
    'surgicals': ('VSR',),
    'sustainable': ('SAF',),
    'sustainables': ('SAF',),
    'sy': ('EBS', 'SAF', 'ASE'),
    'sys': ('EBS', 'SAF', 'ASE'),
    'system': ('ABT', 'EBS', 'SAF', 'ASE'),
    'systems': ('ABT', 'EBS', 'SAF', 'ASE'),
    'tech': ('ABT', 'FST', 'TTP', 'STS'),
    'teches': ('ABT', 'FST', 'TTP', 'STS'),
    'technocultural': ('CTS', 'TCS'),
    'technoculturals': ('CTS', 'TCS'),
    'technologies': ('ABT', 'FST', 'TTP', 'STS'),
    'technology': ('ABT', 'FST', 'TTP', 'STS'),
    'term': ('STP',),
    'terms': ('STP',),
    'textile': ('TXC',),
    'textiles': ('TXC',),
    'theories': ('STH', 'CRI'),
    'theory': ('STH', 'CRI'),
    'toxic': ('ETX', 'PHA', 'PTX'),
    'toxicologies': ('ETX', 'PHA', 'PTX'),
    'toxicology': ('ETX', 'PHA', 'PTX'),
    'toxics': ('ETX', 'PHA', 'PTX'),
    'transportation': ('TTP',),
    'transportations': ('TTP',),
    'turkish': ('TSK',),
    'turkishes': ('TSK',),
    'universities': ('UWP',),
    'university': ('UWP',),
    'urdu': ('URD', 'HIN'),
    'urdus': ('URD', 'HIN'),
    'urologies': ('URO',),
    'urology': ('URO',),
    'vegetable': ('VCR',),
    'vegetables': ('VCR',),
    'veterinaries': ('DVM', 'MPM', 'VET', 'VMD'),
    'veterinary': ('DVM', 'MPM', 'VET', 'VMD'),
    'veterinary medicine': ('VMB', 'MPM', 'VSR', 'PMI', 'VME', 'PHR', 'APC'),
    'veterinary medicines': ('VMB', 'MPM', 'VSR', 'PMI', 'VME', 'PHR', 'APC'),
    'viticulture': ('VEN',),
    'viticultures': ('VEN',),
    'vm': ('VMB', 'MPM', 'VSR', 'PMI', 'VME', 'PHR', 'APC'),
    'vms': ('VMB', 'MPM', 'VSR', 'PMI', 'VME', 'PHR', 'APC'),
    'wildlife': ('WFC',),
    'wildlives': ('WFC',),
    "women's": ('WMS',),
    "womens'": ('WMS',),
    'work': ('MGB',),
    'working': ('MGP',),
    'workings': ('MGP',),
    'workload': ('WLD',),
    'workloads': ('WLD',),
    'works': ('MGB',),
    'writing': ('UWP',),
    'writings': ('UWP',)}
