CREATE TABLE subjects(
  tsv tsvector,
  code varchar(3) PRIMARY KEY,
  name text
);
INSERT INTO subjects (code, tsv) VALUES ('SAF', to_tsvector('sustainables agriculture foods system ags sys systems sy ag food sustainable agricultures'));
INSERT INTO subjects (code, tsv) VALUES ('LAW', to_tsvector('law laws'));
INSERT INTO subjects (code, tsv) VALUES ('SSC', to_tsvector('soil scis soils science sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('DAN', to_tsvector('danishes danish'));
INSERT INTO subjects (code, tsv) VALUES ('CHI', to_tsvector('chicana/o chicano chicana/oes std study studies chicanoes stds'));
INSERT INTO subjects (code, tsv) VALUES ('GEL', to_tsvector('geology geologies'));
INSERT INTO subjects (code, tsv) VALUES ('MSC', to_tsvector('scis militaries military science sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('ESP', to_tsvector('scis environmentals policies envir environmental science envirs policy sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('ANS', to_tsvector('animal scis science animals sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('RAL', to_tsvector('rheumatology rheumatologies meds allergy med medicines medicine allergies'));
INSERT INTO subjects (code, tsv) VALUES ('EPP', to_tsvector('epidemiologies meds meds preventatives med med prevs prev preventative epidemiology medicines medicines medicine medicine'));
INSERT INTO subjects (code, tsv) VALUES ('EAS', to_tsvector('asian std asians study studies east stds easts'));
INSERT INTO subjects (code, tsv) VALUES ('EDO', to_tsvector('endocrinology grads graduate groups grad endocrinol graduates endocrinols group endocrinologies grp grps'));
INSERT INTO subjects (code, tsv) VALUES ('ENH', to_tsvector('horticulture environmentals envir environmental envirs horticultures'));
INSERT INTO subjects (code, tsv) VALUES ('HON', to_tsvector('oncology hematologies oncol internals intrl meds internal intrls oncologies med hematology medicines oncols medicine'));
INSERT INTO subjects (code, tsv) VALUES ('POL', to_tsvector('scis political polis science politicals sciences poli sci'));
INSERT INTO subjects (code, tsv) VALUES ('BST', to_tsvector('biostatistics biostatistic'));
INSERT INTO subjects (code, tsv) VALUES ('MPS', to_tsvector('scis mathematics math maths science physical mathematic sciences sci physicals'));
INSERT INTO subjects (code, tsv) VALUES ('ENG', to_tsvector('engineering engineerings'));
INSERT INTO subjects (code, tsv) VALUES ('ERS', to_tsvector('scis environmentals resources envir environmental science envirs resource sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('ARE', to_tsvector('resources agriculturals economics resource econ agricultural economic econs'));
INSERT INTO subjects (code, tsv) VALUES ('DRA', to_tsvector('art dramatics dramatic arts'));
INSERT INTO subjects (code, tsv) VALUES ('NSC', to_tsvector('neurosciences grads graduate groups grad graduates group grp grps neuroscience'));
INSERT INTO subjects (code, tsv) VALUES ('ABI', to_tsvector('biol biols animal biology biologies animals'));
INSERT INTO subjects (code, tsv) VALUES ('ICL', to_tsvector('internationals commercial international law commercials laws'));
INSERT INTO subjects (code, tsv) VALUES ('AHI', to_tsvector('history histories art arts'));
INSERT INTO subjects (code, tsv) VALUES ('OTO', to_tsvector('otolaryngologies meds otolaryngology med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('BMB', to_tsvector('biol biols molec grads moleculars graduate biology grad molecs graduates biologies biochemistry biochemistries molecular'));
INSERT INTO subjects (code, tsv) VALUES ('RMT', to_tsvector('scis range science ranges sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('FOR', to_tsvector('forensics scis forensic science sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('NPB', to_tsvector('behavior physiology neurologies neurobiology neurology physios neurobiologies physiologies behaviors physio'));
INSERT INTO subjects (code, tsv) VALUES ('BCB', to_tsvector('bios bios cells developmentals devs molec dev moleculars biology biology molecs biologies biologies developmental bio bio cell developments development ggs molecular gg'));
INSERT INTO subjects (code, tsv) VALUES ('NUB', to_tsvector('biol biols nutritional grads graduate biology nutritionals groups grad graduates biologies group grp grps'));
INSERT INTO subjects (code, tsv) VALUES ('IRE', to_tsvector('internationals relation international relations'));
INSERT INTO subjects (code, tsv) VALUES ('ARB', to_tsvector('arabic arabics'));
INSERT INTO subjects (code, tsv) VALUES ('CST', to_tsvector('culturals std study studies cultural stds'));
INSERT INTO subjects (code, tsv) VALUES ('STP', to_tsvector('term short abroads program shorts abroad terms programs'));
INSERT INTO subjects (code, tsv) VALUES ('MSA', to_tsvector('middles middle asian std souths south asians study studies east stds easts'));
INSERT INTO subjects (code, tsv) VALUES ('DVM', to_tsvector('clinic veterinaries rotation veterinary rotations clinics clinical clinicals'));
INSERT INTO subjects (code, tsv) VALUES ('JST', to_tsvector('jewishes std jewish study studies stds'));
INSERT INTO subjects (code, tsv) VALUES ('CMN', to_tsvector('communication communications'));
INSERT INTO subjects (code, tsv) VALUES ('LAT', to_tsvector('latin latins'));
INSERT INTO subjects (code, tsv) VALUES ('ABS', to_tsvector('behaviorals applieds science behavioral applied sciences'));
INSERT INTO subjects (code, tsv) VALUES ('EVE', to_tsvector('evolution evolutions ecologies ecology'));
INSERT INTO subjects (code, tsv) VALUES ('ETX', to_tsvector('toxicologies toxic environmentals envir environmental envirs toxics toxicology'));
INSERT INTO subjects (code, tsv) VALUES ('URD', to_tsvector('urdu urdus'));
INSERT INTO subjects (code, tsv) VALUES ('IAD', to_tsvector('internationals developmentals devs dev agriculturals international developmental agricultural developments development'));
INSERT INTO subjects (code, tsv) VALUES ('MGP', to_tsvector('managemnt managemnts working professionls workings managements professionl management'));
INSERT INTO subjects (code, tsv) VALUES ('BPT', to_tsvector('biophotonic biophotonics'));
INSERT INTO subjects (code, tsv) VALUES ('GAS', to_tsvector('gastroenterology internals intrl meds internal intrls gastroenterologies med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('IMD', to_tsvector('intls internals meds meds internal med med intl medicines medicines medicine medicine'));
INSERT INTO subjects (code, tsv) VALUES ('AGC', to_tsvector('chemistries chem environmentals grads graduate grad envir agriculturals graduates environmental envirs chems agricultural chemistry'));
INSERT INTO subjects (code, tsv) VALUES ('PED', to_tsvector('meds pediatric pediatrics med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('AGE', to_tsvector('agriculturals economics econ agricultural economic econs'));
INSERT INTO subjects (code, tsv) VALUES ('PLB', to_tsvector('biol biols biology plants biologies plant'));
INSERT INTO subjects (code, tsv) VALUES ('MUS', to_tsvector('music musics'));
INSERT INTO subjects (code, tsv) VALUES ('EXS', to_tsvector('exercise scis exercises science sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('POM', to_tsvector('pomologies pomology'));
INSERT INTO subjects (code, tsv) VALUES ('CLA', to_tsvector('classics classic'));
INSERT INTO subjects (code, tsv) VALUES ('BPH', to_tsvector('grads graduate groups biophysic grad graduates group grp biophysics grps'));
INSERT INTO subjects (code, tsv) VALUES ('MIB', to_tsvector('grads graduate microbiol groups grad graduates group microbiologies microbiols grp microbiology grps'));
INSERT INTO subjects (code, tsv) VALUES ('AMR', to_tsvector('mngts resources agriculture range agrics agric mngt resource ranges agricultures managements management'));
INSERT INTO subjects (code, tsv) VALUES ('RUS', to_tsvector('russians russian'));
INSERT INTO subjects (code, tsv) VALUES ('RON', to_tsvector('oncology oncol meds radiation oncologies med radiations medicines oncols medicine'));
INSERT INTO subjects (code, tsv) VALUES ('EAE', to_tsvector('engineering scis science aeroes aerospace engineerings aerospaces sciences sci aero'));
INSERT INTO subjects (code, tsv) VALUES ('FSM', to_tsvector('managemnt managemnts foods service services food managements management'));
INSERT INTO subjects (code, tsv) VALUES ('REL', to_tsvector('religions ofs of religion study studies'));
INSERT INTO subjects (code, tsv) VALUES ('EPI', to_tsvector('epidemiologies grads graduate groups grad graduates group grp grps epidemiology'));
INSERT INTO subjects (code, tsv) VALUES ('PBI', to_tsvector('biol biols grads graduate biology groups grad graduates plants biologies group grp plant grps'));
INSERT INTO subjects (code, tsv) VALUES ('HEB', to_tsvector('hebrews hebrew'));
INSERT INTO subjects (code, tsv) VALUES ('MPM', to_tsvector('vm veterinaries veterinary medicine meds veterinary vms veterinary medicines med preventive preventives medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('ECN', to_tsvector('economics econ economic econs'));
INSERT INTO subjects (code, tsv) VALUES ('ECH', to_tsvector('engineering chemicals chemical engineerings'));
INSERT INTO subjects (code, tsv) VALUES ('FRE', to_tsvector('frenches french'));
INSERT INTO subjects (code, tsv) VALUES ('CSM', to_tsvector('managemnt scis managemnts crops science crop sciences managements sci management'));
INSERT INTO subjects (code, tsv) VALUES ('EEC', to_tsvector('engineering computer electrical electricals engineerings compus computers compu'));
INSERT INTO subjects (code, tsv) VALUES ('AST', to_tsvector('astronomy astronomies'));
INSERT INTO subjects (code, tsv) VALUES ('SPA', to_tsvector('spanish spanishes'));
INSERT INTO subjects (code, tsv) VALUES ('UWP', to_tsvector('universities university program writing writings programs'));
INSERT INTO subjects (code, tsv) VALUES ('FRS', to_tsvector('seminar freshmen seminars freshman'));
INSERT INTO subjects (code, tsv) VALUES ('ABT', to_tsvector('system applieds technologies biologicals biological teches systems applied tech technology'));
INSERT INTO subjects (code, tsv) VALUES ('HNR', to_tsvector('honors challenges challenge honor'));
INSERT INTO subjects (code, tsv) VALUES ('PMR', to_tsvector('rehab rehabilitation rehabs meds meds rehabilitations med med medicines medicines physical medicine medicine physicals'));
INSERT INTO subjects (code, tsv) VALUES ('EDU', to_tsvector('educations education'));
INSERT INTO subjects (code, tsv) VALUES ('HUM', to_tsvector('humanity humanities'));
INSERT INTO subjects (code, tsv) VALUES ('MHI', to_tsvector('informatics health informatic healths hlth hlths'));
INSERT INTO subjects (code, tsv) VALUES ('BIS', to_tsvector('biologicals biological science sciences'));
INSERT INTO subjects (code, tsv) VALUES ('SOC', to_tsvector('sociology sociologies'));
INSERT INTO subjects (code, tsv) VALUES ('PTX', to_tsvector('toxicologies toxic pharmacol grads graduate grad pharmacols graduates pharmacologies toxics pharmacology toxicology'));
INSERT INTO subjects (code, tsv) VALUES ('EME', to_tsvector('mechanical engineering mechanicals engineerings'));
INSERT INTO subjects (code, tsv) VALUES ('CAN', to_tsvector('cantonese cantonese'));
INSERT INTO subjects (code, tsv) VALUES ('EMR', to_tsvector('emergency internals intrl meds meds emergencies internal intrls med med medicines medicines medicine medicine'));
INSERT INTO subjects (code, tsv) VALUES ('MCP', to_tsvector('physiology cells molec internals moleculars molecs internal int ints physios physiologies cell molecular physio'));
INSERT INTO subjects (code, tsv) VALUES ('STH', to_tsvector('socials history comparatives comparative histories compar social compars theories theory'));
INSERT INTO subjects (code, tsv) VALUES ('BIT', to_tsvector('biotechnology biotechnologies'));
INSERT INTO subjects (code, tsv) VALUES ('ANE', to_tsvector('anesthesiologies meds med anesthesiology medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('ECL', to_tsvector('ecologies ecology'));
INSERT INTO subjects (code, tsv) VALUES ('DES', to_tsvector('desig design desigs designs'));
INSERT INTO subjects (code, tsv) VALUES ('EAL', to_tsvector('livermores engineering scis applieds lvrmors science lvrmor livermore applied engineerings sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('MST', to_tsvector('medieval std study studies medievals stds'));
INSERT INTO subjects (code, tsv) VALUES ('LIN', to_tsvector('linguistic linguistics'));
INSERT INTO subjects (code, tsv) VALUES ('MMI', to_tsvector('meds microbiol medicals microbiologies microbiols med microbiology medicines medical medicine'));
INSERT INTO subjects (code, tsv) VALUES ('HIS', to_tsvector('history histories'));
INSERT INTO subjects (code, tsv) VALUES ('COM', to_tsvector('literatures comparatives comparative compar compars literature'));
INSERT INTO subjects (code, tsv) VALUES ('PMI', to_tsvector('pathologies vm veterinary medicine microbiol vms immunologies microbiologies veterinary medicines microbiols microbiology immuns pathology immun immunology'));
INSERT INTO subjects (code, tsv) VALUES ('IDI', to_tsvector('infectiouses internals intrl meds internal disease diseases intrls dis med di infectious medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('ACC', to_tsvector('professional accountancy prof accountancies profs professionals'));
INSERT INTO subjects (code, tsv) VALUES ('SUR', to_tsvector('meds surgeries med surgery medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('PLS', to_tsvector('scis science plants plant sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('NSU', to_tsvector('meds neurosurgeries neurosurgery med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('FST', to_tsvector('scis foods technologies teches science tech technology food sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('HMR', to_tsvector('human right humans rights'));
INSERT INTO subjects (code, tsv) VALUES ('VET', to_tsvector('school veterinaries meds veterinary ofs of med schools medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('WFC', to_tsvector('biol biols conservations conserv conservation biology conservs biologies fish fish wildlife wildlives'));
INSERT INTO subjects (code, tsv) VALUES ('NAS', to_tsvector('american std americans native study studies stds natives'));
INSERT INTO subjects (code, tsv) VALUES ('ITA', to_tsvector('italian italians'));
INSERT INTO subjects (code, tsv) VALUES ('EAP', to_tsvector('educations abroads education program abroad programs'));
INSERT INTO subjects (code, tsv) VALUES ('JPN', to_tsvector('japanese japanese'));
INSERT INTO subjects (code, tsv) VALUES ('CNE', to_tsvector('consumer economics consumers econ economic econs'));
INSERT INTO subjects (code, tsv) VALUES ('NUT', to_tsvector('nutritions nutr nutrs nutrition'));
INSERT INTO subjects (code, tsv) VALUES ('ASE', to_tsvector('environmentals system envir agriculturals sys environmental envirs systems sy agricultural'));
INSERT INTO subjects (code, tsv) VALUES ('SAS', to_tsvector('scis society science societies sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('BIM', to_tsvector('engineering biomedical biomedicals engineerings'));
INSERT INTO subjects (code, tsv) VALUES ('NEM', to_tsvector('nematologies nematology'));
INSERT INTO subjects (code, tsv) VALUES ('OEH', to_tsvector('health envrns occupationals environmentals meds healths environmental envrn med hlth occupational medicines medicine hlths'));
INSERT INTO subjects (code, tsv) VALUES ('PHI', to_tsvector('philosophy philosophies'));
INSERT INTO subjects (code, tsv) VALUES ('OBG', to_tsvector('meds obstetrics med gynecologies medicines obstetric medicine gynecology'));
INSERT INTO subjects (code, tsv) VALUES ('RST', to_tsvector('religious std study studies religiouses stds'));
INSERT INTO subjects (code, tsv) VALUES ('URO', to_tsvector('urology meds urologies med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('MIC', to_tsvector('microbiol microbiologies microbiols microbiology'));
INSERT INTO subjects (code, tsv) VALUES ('AED', to_tsvector('educations education agriculturals agricultural'));
INSERT INTO subjects (code, tsv) VALUES ('CPS', to_tsvector('clinic meds clinics psychologies psychology med clinical medicines clinicals medicine'));
INSERT INTO subjects (code, tsv) VALUES ('CNS', to_tsvector('consumer science consumers sciences'));
INSERT INTO subjects (code, tsv) VALUES ('DER', to_tsvector('meds dermatologies dermatology med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('HYD', to_tsvector('scis hydrologic science hydrologics sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('MAT', to_tsvector('mathematics math maths mathematic'));
INSERT INTO subjects (code, tsv) VALUES ('SPH', to_tsvector('health meds healths science public med hlth medicines sciences publics medicine hlths'));
INSERT INTO subjects (code, tsv) VALUES ('HIN', to_tsvector('urdu hindi urdus hindis'));
INSERT INTO subjects (code, tsv) VALUES ('MCB', to_tsvector('biol biols molec moleculars biology cellulars molecs cellular biologies molecular'));
INSERT INTO subjects (code, tsv) VALUES ('STA', to_tsvector('statistic statistics'));
INSERT INTO subjects (code, tsv) VALUES ('FAP', to_tsvector('families meds med practices medicines practice family medicine'));
INSERT INTO subjects (code, tsv) VALUES ('ANG', to_tsvector('animal animals genetic genetics'));
INSERT INTO subjects (code, tsv) VALUES ('CRO', to_tsvector('croatian croatians'));
INSERT INTO subjects (code, tsv) VALUES ('VCR', to_tsvector('vegetable vegetables crops crop'));
INSERT INTO subjects (code, tsv) VALUES ('TCS', to_tsvector('technocultural technoculturals std study studies stds'));
INSERT INTO subjects (code, tsv) VALUES ('RNU', to_tsvector('meds meds radiology med med nuclears nuclear radiologies medicines medicines medicine medicine'));
INSERT INTO subjects (code, tsv) VALUES ('VMD', to_tsvector('veterinaries meds veterinary med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('NEU', to_tsvector('neurologies meds neurobiology neurology neurobiologies med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('CEL', to_tsvector('celtic celtics'));
INSERT INTO subjects (code, tsv) VALUES ('LDA', to_tsvector('landscapes architectures landscape architecture'));
INSERT INTO subjects (code, tsv) VALUES ('AAS', to_tsvector('american std americans study studies african african stds africans africans'));
INSERT INTO subjects (code, tsv) VALUES ('MGB', to_tsvector('managemnt professional bays managemnts works prof bay work area areas profs professionals managements management'));
INSERT INTO subjects (code, tsv) VALUES ('IPM', to_tsvector('managemnt pests managemnts pest integrateds integrated managements management'));
INSERT INTO subjects (code, tsv) VALUES ('ART', to_tsvector('studios studio art arts'));
INSERT INTO subjects (code, tsv) VALUES ('IST', to_tsvector('integrateds std integrated study studies stds'));
INSERT INTO subjects (code, tsv) VALUES ('CHE', to_tsvector('chemistries chem chems chemistry'));
INSERT INTO subjects (code, tsv) VALUES ('PAS', to_tsvector('assistant assistants physician std study studies physicians stds'));
INSERT INTO subjects (code, tsv) VALUES ('AVS', to_tsvector('science avians sciences avian'));
INSERT INTO subjects (code, tsv) VALUES ('HUN', to_tsvector('hungarians hungarian'));
INSERT INTO subjects (code, tsv) VALUES ('VME', to_tsvector('vm epidemiologies veterinary medicine meds vms veterinary medicines med epidemiology medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('GMD', to_tsvector('internals intrl meds meds general internal intrls generals med med medicines medicines medicine medicine'));
INSERT INTO subjects (code, tsv) VALUES ('MAE', to_tsvector('mechanical engineering mechanicals aeroes aerospace engineerings aerospaces aero'));
INSERT INTO subjects (code, tsv) VALUES ('CLH', to_tsvector('clinic research clinics researches clinical clinicals'));
INSERT INTO subjects (code, tsv) VALUES ('VEN', to_tsvector('viticultures viticulture enologies enology'));
INSERT INTO subjects (code, tsv) VALUES ('PSY', to_tsvector('psychiatries meds med psychiatry medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('MPH', to_tsvector('health master ofs of masters healths public hlth publics hlths'));
INSERT INTO subjects (code, tsv) VALUES ('PSU', to_tsvector('plastics meds plastic surgeries med surgery medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('IMM', to_tsvector('grads graduate groups grad graduates immunologies group grp immuns grps immun immunology'));
INSERT INTO subjects (code, tsv) VALUES ('CRD', to_tsvector('develpmnt regionals develpmnts community communities regional developments development'));
INSERT INTO subjects (code, tsv) VALUES ('VSR', to_tsvector('surgicals scis vm veterinary medicine surgical radiologicals vms science radiological veterinary medicines sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('VMB', to_tsvector('vm molec moleculars biosciences veterinary medicine molecs bioscience vms veterinary medicines molecular'));
INSERT INTO subjects (code, tsv) VALUES ('NEP', to_tsvector('internals intrl meds internal intrls nephrology nephrologies med medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('NCM', to_tsvector('clinic internals intrl meds nutritions internal metabolism intrls nutr clinics metab med metabs clinical medicines metabolisms nutrs clinicals medicine nutrition'));
INSERT INTO subjects (code, tsv) VALUES ('CDM', to_tsvector('cinemas digitals digital cinema medias media'));
INSERT INTO subjects (code, tsv) VALUES ('LAH', to_tsvector('american hemispheric americans hemispherics latin latins'));
INSERT INTO subjects (code, tsv) VALUES ('CTS', to_tsvector('technocultural studs cinemas technoculturals study cinema studies stud'));
INSERT INTO subjects (code, tsv) VALUES ('HPS', to_tsvector('scis history philosophy histories ofs of philosophies science sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('ESM', to_tsvector('managemnt scis environmentals managemnts envir environmental science envirs sciences managements sci management'));
INSERT INTO subjects (code, tsv) VALUES ('OPT', to_tsvector('ophthalmology meds med ophthalmologies medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('PBG', to_tsvector('biol biols population populations biology biologies'));
INSERT INTO subjects (code, tsv) VALUES ('RDI', to_tsvector('diagnostic diagnostics meds radiology med radiologies medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('ATM', to_tsvector('atmospheric scis science atmospherics sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('POR', to_tsvector('portuguese portugueses'));
INSERT INTO subjects (code, tsv) VALUES ('ABG', to_tsvector('biol biols animal grads graduate biology grad gps graduates biologies animals gp'));
INSERT INTO subjects (code, tsv) VALUES ('HRT', to_tsvector('horticulture horticultures'));
INSERT INTO subjects (code, tsv) VALUES ('PHY', to_tsvector('physic physics'));
INSERT INTO subjects (code, tsv) VALUES ('PLP', to_tsvector('pathologies plants plant pathology'));
INSERT INTO subjects (code, tsv) VALUES ('AGR', to_tsvector('agronomy agronomies'));
INSERT INTO subjects (code, tsv) VALUES ('TSK', to_tsvector('turkish turkishes'));
INSERT INTO subjects (code, tsv) VALUES ('PHE', to_tsvector('educations education physical physicals'));
INSERT INTO subjects (code, tsv) VALUES ('GEO', to_tsvector('geographies geography'));
INSERT INTO subjects (code, tsv) VALUES ('EXB', to_tsvector('biol biols exercise biology exercises biologies'));
INSERT INTO subjects (code, tsv) VALUES ('EAD', to_tsvector('engineering scis applieds science applied davis engineerings davi sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('ANB', to_tsvector('behavior animal grads graduate grad gps graduates animals behaviors gp'));
INSERT INTO subjects (code, tsv) VALUES ('PHA', to_tsvector('toxicologies toxic pharmacol meds medicals pharmacols pharmacologies med toxics medicines medical pharmacology medicine toxicology'));
INSERT INTO subjects (code, tsv) VALUES ('NAC', to_tsvector('natures cultures culture nature'));
INSERT INTO subjects (code, tsv) VALUES ('PFS', to_tsvector('performances performance grads graduate groups grad std graduates group study grp studies grps stds'));
INSERT INTO subjects (code, tsv) VALUES ('PHR', to_tsvector('health vm population reproductives populations veterinary medicine reproductive vms healths veterinary medicines reprod hlth reprods hlths'));
INSERT INTO subjects (code, tsv) VALUES ('ENM', to_tsvector('endocrinology internals intrl meds endocrinol internal metabolism intrls endocrinols endocrinologies metab med metabs medicines metabolisms medicine'));
INSERT INTO subjects (code, tsv) VALUES ('CAR', to_tsvector('internals intrl meds internal intrls cardiology med cardiologies medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('HPH', to_tsvector('physiology human meds humans physios med physiologies medicines medicine physio'));
INSERT INTO subjects (code, tsv) VALUES ('WMS', to_tsvector('women's std study womens' studies stds'));
INSERT INTO subjects (code, tsv) VALUES ('WLD', to_tsvector('workload workloads'));
INSERT INTO subjects (code, tsv) VALUES ('CMH', to_tsvector('intls health internals meds internal healths community med communities intl hlth medicines medicine hlths'));
INSERT INTO subjects (code, tsv) VALUES ('STS', to_tsvector('scis std technologies teches science study studies tech technology stds sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('CLR', to_tsvector('at ats college rue colleges las la rues'));
INSERT INTO subjects (code, tsv) VALUES ('PUL', to_tsvector('internals pulmonaries intrl meds internal intrls med medicines pulmonary medicine'));
INSERT INTO subjects (code, tsv) VALUES ('GRK', to_tsvector('greeks greek'));
INSERT INTO subjects (code, tsv) VALUES ('ECS', to_tsvector('engineering scis computer science engineerings compus computers sciences sci compu'));
INSERT INTO subjects (code, tsv) VALUES ('FPS', to_tsvector('fiber scis polymers fibers science polymer sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('ECI', to_tsvector('engineering environmentals environ environmental civils engineerings environs civil'));
INSERT INTO subjects (code, tsv) VALUES ('CDB', to_tsvector('biol biols cells ds developmentals developmentals v es grads graduate biology vs grad d graduates biologies developmental developmental e cell developments development'));
INSERT INTO subjects (code, tsv) VALUES ('ENT', to_tsvector('entomologies entomology'));
INSERT INTO subjects (code, tsv) VALUES ('MDI', to_tsvector('informatics informatic medicals medical'));
INSERT INTO subjects (code, tsv) VALUES ('MGT', to_tsvector('managemnt managemnts managements management'));
INSERT INTO subjects (code, tsv) VALUES ('FMS', to_tsvector('std films study studies film stds'));
INSERT INTO subjects (code, tsv) VALUES ('AMS', to_tsvector('american std americans study studies stds'));
INSERT INTO subjects (code, tsv) VALUES ('OSU', to_tsvector('orthopaedics meds orthopaedic surgeries med surgery medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('APC', to_tsvector('anatomies anats physiology bios cells vm anat veterinary medicine biology vms biologies physiols veterinary medicines physiol physiologies bio cell anatomy'));
INSERT INTO subjects (code, tsv) VALUES ('GGG', to_tsvector('grads graduate groups grad graduates group grp grps genetic genetics'));
INSERT INTO subjects (code, tsv) VALUES ('CRI', to_tsvector('empha emphases emphas desig critical design theories theory criticals desigs designs emphasis'));
INSERT INTO subjects (code, tsv) VALUES ('ANT', to_tsvector('anthropology anthropologies'));
INSERT INTO subjects (code, tsv) VALUES ('PGG', to_tsvector('physiology grads graduate groups grad physios graduates group grp physiologies grps physio'));
INSERT INTO subjects (code, tsv) VALUES ('HDE', to_tsvector('develpmnt human humans develpmnts developments development'));
INSERT INTO subjects (code, tsv) VALUES ('CHN', to_tsvector('chinese chinese'));
INSERT INTO subjects (code, tsv) VALUES ('CHA', to_tsvector('anatomies biol anats biols cells anat human biology meds humans biologies med medicines cell medicine anatomy'));
INSERT INTO subjects (code, tsv) VALUES ('GER', to_tsvector('germen german'));
INSERT INTO subjects (code, tsv) VALUES ('NGG', to_tsvector('grads graduate groups grad nutritions graduates nutr group grp grps nutrs nutrition'));
INSERT INTO subjects (code, tsv) VALUES ('ECM', to_tsvector('engineering chemicals materials chemical material engineerings'));
INSERT INTO subjects (code, tsv) VALUES ('PSC', to_tsvector('psychologies psychology'));
INSERT INTO subjects (code, tsv) VALUES ('PPP', to_tsvector('pests pest protections protection mangmt plants plant mangmts managements management'));
INSERT INTO subjects (code, tsv) VALUES ('ENL', to_tsvector('english englishes'));
INSERT INTO subjects (code, tsv) VALUES ('ENP', to_tsvector('managemnt environmentals managemnts envir environmental envirs plan plans managements management'));
INSERT INTO subjects (code, tsv) VALUES ('PMD', to_tsvector('pathologies meds med pathology medicines medicine'));
INSERT INTO subjects (code, tsv) VALUES ('EBS', to_tsvector('engineering system sys biologicals biological systems sy engineerings'));
INSERT INTO subjects (code, tsv) VALUES ('DEB', to_tsvector('empha emphases emphas desig biotechnology biotechnologies design desigs designs emphasis'));
INSERT INTO subjects (code, tsv) VALUES ('NRS', to_tsvector('nursings nursing'));
INSERT INTO subjects (code, tsv) VALUES ('EJS', to_tsvector('economy justice society economies societies justices'));
INSERT INTO subjects (code, tsv) VALUES ('EST', to_tsvector('environmentals std envir environmental envirs study studies stds'));
INSERT INTO subjects (code, tsv) VALUES ('TXC', to_tsvector('textiles clothing clothings textile'));
INSERT INTO subjects (code, tsv) VALUES ('TTP', to_tsvector('transportation policies technologies teches transportations policy tech technology'));
INSERT INTO subjects (code, tsv) VALUES ('BCM', to_tsvector('chemistries chem meds biologicals biological med chems medicines medicine chemistry'));
INSERT INTO subjects (code, tsv) VALUES ('ASA', to_tsvector('american asian std americans asians study studies stds'));
INSERT INTO subjects (code, tsv) VALUES ('GDB', to_tsvector('biol biols global biology disease diseases biologies globals'));
INSERT INTO subjects (code, tsv) VALUES ('EMS', to_tsvector('engineering scis materials science material engineerings sciences sci'));
INSERT INTO subjects (code, tsv) VALUES ('MDS', to_tsvector('scis meds medicals science med medicines medical sciences sci medicine'));
;