ALTER TABLE subjects ADD pretty_name text;
UPDATE subjects SET name ='African American & African Std' WHERE code = 'AAS';
UPDATE subjects SET name ='Agric Mngt & Range Resources' WHERE code = 'AMR';
UPDATE subjects SET name ='Agricultural & Envir Chem Grad' WHERE code = 'AGC';
UPDATE subjects SET name ='Agricultural & Resource Econ' WHERE code = 'ARE';
UPDATE subjects SET name ='Agricultural Economics' WHERE code = 'AGE';
UPDATE subjects SET name ='Agricultural Education' WHERE code = 'AED';
UPDATE subjects SET name ='Agricultural Systems & Envir' WHERE code = 'ASE';
UPDATE subjects SET name ='Agronomy' WHERE code = 'AGR';
UPDATE subjects SET name ='American Studies' WHERE code = 'AMS';
UPDATE subjects SET name ='Animal Behavior (Graduate Gp)' WHERE code = 'ANB';
UPDATE subjects SET name ='Animal Biology' WHERE code = 'ABI';
UPDATE subjects SET name ='Animal Biology Grad Gp' WHERE code = 'ABG';
UPDATE subjects SET name ='Animal Genetics' WHERE code = 'ANG';
UPDATE subjects SET name ='Animal Science' WHERE code = 'ANS';
UPDATE subjects SET name ='Anthropology' WHERE code = 'ANT';
UPDATE subjects SET name ='Applied Behavioral Sciences' WHERE code = 'ABS';
UPDATE subjects SET name ='Applied Biological System Tech' WHERE code = 'ABT';
UPDATE subjects SET name ='Arabic' WHERE code = 'ARB';
UPDATE subjects SET name ='Art History' WHERE code = 'AHI';
UPDATE subjects SET name ='Art Studio' WHERE code = 'ART';
UPDATE subjects SET name ='Asian American Studies' WHERE code = 'ASA';
UPDATE subjects SET name ='Astronomy' WHERE code = 'AST';
UPDATE subjects SET name ='Atmospheric Science' WHERE code = 'ATM';
UPDATE subjects SET name ='Avian Sciences' WHERE code = 'AVS';
UPDATE subjects SET name ='Bio, Molec, Cell, Dev Bio GG' WHERE code = 'BCB';
UPDATE subjects SET name ='Biochemistry & Molec Biol Grad' WHERE code = 'BMB';
UPDATE subjects SET name ='Biological Sciences' WHERE code = 'BIS';
UPDATE subjects SET name ='Biophotonics' WHERE code = 'BPT';
UPDATE subjects SET name ='Biophysics (Graduate Group)' WHERE code = 'BPH';
UPDATE subjects SET name ='Biostatistics' WHERE code = 'BST';
UPDATE subjects SET name ='Biotechnology' WHERE code = 'BIT';
UPDATE subjects SET name ='Biotechnology (Desig Emphasis)' WHERE code = 'DEB';
UPDATE subjects SET name ='Cantonese' WHERE code = 'CAN';
UPDATE subjects SET name ='Cell & Developmental Biol Grad' WHERE code = 'CDB';
UPDATE subjects SET name ='Celtic' WHERE code = 'CEL';
UPDATE subjects SET name ='Chemistry' WHERE code = 'CHE';
UPDATE subjects SET name ='Chicano Studies' WHERE code = 'CHI';
UPDATE subjects SET name ='Chinese' WHERE code = 'CHN';
UPDATE subjects SET name ='Cinema & Technocultural Stud' WHERE code = 'CTS';
UPDATE subjects SET name ='Cinema and Digital Media' WHERE code = 'CDM';
UPDATE subjects SET name ='Classics' WHERE code = 'CLA';
UPDATE subjects SET name ='Clinical Research' WHERE code = 'CLH';
UPDATE subjects SET name ='Colleges at La Rue' WHERE code = 'CLR';
UPDATE subjects SET name ='Cognitive Science' WHERE code = 'CGS';
UPDATE subjects SET name ='Communication' WHERE code = 'CMN';
UPDATE subjects SET name ='Community & Regional Develpmnt' WHERE code = 'CRD';
UPDATE subjects SET name ='Comparative Literature' WHERE code = 'COM';
UPDATE subjects SET name ='Consumer Economics' WHERE code = 'CNE';
UPDATE subjects SET name ='Consumer Sciences' WHERE code = 'CNS';
UPDATE subjects SET name ='Critical Theory (Desig Emphas)' WHERE code = 'CRI';
UPDATE subjects SET name ='Croatian' WHERE code = 'CRO';
UPDATE subjects SET name ='Crop Science & Management' WHERE code = 'CSM';
UPDATE subjects SET name ='Cultural Studies' WHERE code = 'CST';
UPDATE subjects SET name ='Danish' WHERE code = 'DAN';
UPDATE subjects SET name ='Design' WHERE code = 'DES';
UPDATE subjects SET name ='Dramatic Art' WHERE code = 'DRA';
UPDATE subjects SET name ='East Asian Studies' WHERE code = 'EAS';
UPDATE subjects SET name ='Ecology' WHERE code = 'ECL';
UPDATE subjects SET name ='Economics' WHERE code = 'ECN';
UPDATE subjects SET name ='Economy, Justice & Society' WHERE code = 'EJS';
UPDATE subjects SET name ='Education' WHERE code = 'EDU';
UPDATE subjects SET name ='Education Abroad Program' WHERE code = 'EAP';
UPDATE subjects SET name ='Endocrinology (Graduate Group)' WHERE code = 'EDO';
UPDATE subjects SET name ='Engineering' WHERE code = 'ENG';
UPDATE subjects SET name ='Engineering Aerospace Sci' WHERE code = 'EAE';
UPDATE subjects SET name ='Engineering Applied Sci-Davis' WHERE code = 'EAD';
UPDATE subjects SET name ='Engineering Applied Sci-Lvrmor' WHERE code = 'EAL';
UPDATE subjects SET name ='Engineering Biological Systems' WHERE code = 'EBS';
UPDATE subjects SET name ='Engineering Biomedical' WHERE code = 'BIM';
UPDATE subjects SET name ='Engineering Chemical' WHERE code = 'ECH';
UPDATE subjects SET name ='Engineering Chemical-Materials' WHERE code = 'ECM';
UPDATE subjects SET name ='Engineering Civil & Environ' WHERE code = 'ECI';
UPDATE subjects SET name ='Engineering Computer Science' WHERE code = 'ECS';
UPDATE subjects SET name ='Engineering Electrical & Compu' WHERE code = 'EEC';
UPDATE subjects SET name ='Engineering Materials Science' WHERE code = 'EMS';
UPDATE subjects SET name ='Engineering Mechanical' WHERE code = 'EME';
UPDATE subjects SET name ='Engineering Mechanical & Aero' WHERE code = 'MAE';
UPDATE subjects SET name ='English' WHERE code = 'ENL';
UPDATE subjects SET name ='Entomology' WHERE code = 'ENT';
UPDATE subjects SET name ='Environmental Horticulture' WHERE code = 'ENH';
UPDATE subjects SET name ='Environmental Plan & Managemnt' WHERE code = 'ENP';
UPDATE subjects SET name ='Environmental Resource Science' WHERE code = 'ERS';
UPDATE subjects SET name ='Environmental Sci & Management' WHERE code = 'ESM';
UPDATE subjects SET name ='Environmental Science & Policy' WHERE code = 'ESP';
UPDATE subjects SET name ='Environmental Studies' WHERE code = 'EST';
UPDATE subjects SET name ='Environmental Toxicology' WHERE code = 'ETX';
UPDATE subjects SET name ='Epidemiology (Graduate Group)' WHERE code = 'EPI';
UPDATE subjects SET name ='Evolution and Ecology' WHERE code = 'EVE';
UPDATE subjects SET name ='Exercise Biology' WHERE code = 'EXB';
UPDATE subjects SET name ='Exercise Science' WHERE code = 'EXS';
UPDATE subjects SET name ='Fiber And Polymer Science' WHERE code = 'FPS';
UPDATE subjects SET name ='Film Studies' WHERE code = 'FMS';
UPDATE subjects SET name ='Food Science & Technology' WHERE code = 'FST';
UPDATE subjects SET name ='Food Service Management' WHERE code = 'FSM';
UPDATE subjects SET name ='Forensic Science' WHERE code = 'FOR';
UPDATE subjects SET name ='French' WHERE code = 'FRE';
UPDATE subjects SET name ='Freshman Seminar' WHERE code = 'FRS';
UPDATE subjects SET name ='Genetics (Graduate Group)' WHERE code = 'GGG';
UPDATE subjects SET name ='Geography' WHERE code = 'GEO';
UPDATE subjects SET name ='Geology' WHERE code = 'GEL';
UPDATE subjects SET name ='German' WHERE code = 'GER';
UPDATE subjects SET name ='Global Disease Biology' WHERE code = 'GDB';
UPDATE subjects SET name ='Greek' WHERE code = 'GRK';
UPDATE subjects SET name ='Health Informatics' WHERE code = 'MHI';
UPDATE subjects SET name ='Hebrew' WHERE code = 'HEB';
UPDATE subjects SET name ='Hindi/Urdu' WHERE code = 'HIN';
UPDATE subjects SET name ='History' WHERE code = 'HIS';
UPDATE subjects SET name ='History & Philosophy of Sci.' WHERE code = 'HPS';
UPDATE subjects SET name ='Honors Challenge' WHERE code = 'HNR';
UPDATE subjects SET name ='Horticulture' WHERE code = 'HRT';
UPDATE subjects SET name ='Human Development' WHERE code = 'HDE';
UPDATE subjects SET name ='Human Rights' WHERE code = 'HMR';
UPDATE subjects SET name ='Humanities' WHERE code = 'HUM';
UPDATE subjects SET name ='Hungarian' WHERE code = 'HUN';
UPDATE subjects SET name ='Hydrologic Science' WHERE code = 'HYD';
UPDATE subjects SET name ='Immunology (Graduate Group)' WHERE code = 'IMM';
UPDATE subjects SET name ='Integrated Pest Management' WHERE code = 'IPM';
UPDATE subjects SET name ='Integrated Studies' WHERE code = 'IST';
UPDATE subjects SET name ='International Agricultural Dev' WHERE code = 'IAD';
UPDATE subjects SET name ='International Commercial Law' WHERE code = 'ICL';
UPDATE subjects SET name ='International Relations' WHERE code = 'IRE';
UPDATE subjects SET name ='Italian' WHERE code = 'ITA';
UPDATE subjects SET name ='Japanese' WHERE code = 'JPN';
UPDATE subjects SET name ='Jewish Studies' WHERE code = 'JST';
UPDATE subjects SET name ='Landscape Architecture' WHERE code = 'LDA';
UPDATE subjects SET name ='Latin' WHERE code = 'LAT';
UPDATE subjects SET name ='Latin American & Hemispheric' WHERE code = 'LAH';
UPDATE subjects SET name ='Law' WHERE code = 'LAW';
UPDATE subjects SET name ='Linguistics' WHERE code = 'LIN';
UPDATE subjects SET name ='Management' WHERE code = 'MGT';
UPDATE subjects SET name ='Management Work Prof Bay Area' WHERE code = 'MGB';
UPDATE subjects SET name ='Management Working Professionl' WHERE code = 'MGP';
UPDATE subjects SET name ='Master of Public Health' WHERE code = 'MPH';
UPDATE subjects SET name ='Math & Physical Sci' WHERE code = 'MPS';
UPDATE subjects SET name ='Mathematics' WHERE code = 'MAT';
UPDATE subjects SET name ='Med - Anesthesiology' WHERE code = 'ANE';
UPDATE subjects SET name ='Med - Biological Chemistry' WHERE code = 'BCM';
UPDATE subjects SET name ='Med - Cell Biol & Human Anat' WHERE code = 'CHA';
UPDATE subjects SET name ='Med - Clinical Psychology' WHERE code = 'CPS';
UPDATE subjects SET name ='Med - Community & Intl Health' WHERE code = 'CMH';
UPDATE subjects SET name ='Med - Dermatology' WHERE code = 'DER';
UPDATE subjects SET name ='Med - Epidemiology & Prev Med' WHERE code = 'EPP';
UPDATE subjects SET name ='Med - Family Practice' WHERE code = 'FAP';
UPDATE subjects SET name ='Med - Human Physiology' WHERE code = 'HPH';
UPDATE subjects SET name ='Med - Internal Medicine' WHERE code = 'IMD';
UPDATE subjects SET name ='Med - Intrl WHERE code = Cardiology' WHERE code = 'CAR';
UPDATE subjects SET name ='Med - Intrl WHERE code = Clinic Nutr&Metab' WHERE code = 'NCM';
UPDATE subjects SET name ='Med - Intrl WHERE code = Emergency Med' WHERE code = 'EMR';
UPDATE subjects SET name ='Med - Intrl WHERE code = Endocrinol &Metab' WHERE code = 'ENM';
UPDATE subjects SET name ='Med - Intrl WHERE code = Gastroenterology' WHERE code = 'GAS';
UPDATE subjects SET name ='Med - Intrl WHERE code = General Medicine' WHERE code = 'GMD';
UPDATE subjects SET name ='Med - Intrl WHERE code = Hematology-Oncol' WHERE code = 'HON';
UPDATE subjects SET name ='Med - Intrl WHERE code = Infectious Dis' WHERE code = 'IDI';
UPDATE subjects SET name ='Med - Intrl WHERE code = Nephrology' WHERE code = 'NEP';
UPDATE subjects SET name ='Med - Intrl WHERE code = Pulmonary' WHERE code = 'PUL';
UPDATE subjects SET name ='Med - Medical Microbiology' WHERE code = 'MMI';
UPDATE subjects SET name ='Med - Medical Pharmacol &Toxic' WHERE code = 'PHA';
UPDATE subjects SET name ='Med - Medical Science' WHERE code = 'MDS';
UPDATE subjects SET name ='Med - Neurology' WHERE code = 'NEU';
UPDATE subjects SET name ='Med - Neurosurgery' WHERE code = 'NSU';
UPDATE subjects SET name ='Med - Obstetrics & Gynecology' WHERE code = 'OBG';
UPDATE subjects SET name ='Med - Occupational &Envrn Hlth' WHERE code = 'OEH';
UPDATE subjects SET name ='Med - Ophthalmology' WHERE code = 'OPT';
UPDATE subjects SET name ='Med - Orthopaedic Surgery' WHERE code = 'OSU';
UPDATE subjects SET name ='Med - Otolaryngology' WHERE code = 'OTO';
UPDATE subjects SET name ='Med - Pathology' WHERE code = 'PMD';
UPDATE subjects SET name ='Med - Pediatrics' WHERE code = 'PED';
UPDATE subjects SET name ='Med - Physical Medicine &Rehab' WHERE code = 'PMR';
UPDATE subjects SET name ='Med - Plastic Surgery' WHERE code = 'PSU';
UPDATE subjects SET name ='Med - Psychiatry' WHERE code = 'PSY';
UPDATE subjects SET name ='Med - Public Health Sciences' WHERE code = 'SPH';
UPDATE subjects SET name ='Med - Radiation Oncology' WHERE code = 'RON';
UPDATE subjects SET name ='Med - Radiology (Diagnostic)' WHERE code = 'RDI';
UPDATE subjects SET name ='Med - Radiology-Nuclear Med' WHERE code = 'RNU';
UPDATE subjects SET name ='Med - Rheumatology (Allergy)' WHERE code = 'RAL';
UPDATE subjects SET name ='Med - Surgery' WHERE code = 'SUR';
UPDATE subjects SET name ='Med - Urology' WHERE code = 'URO';
UPDATE subjects SET name ='Medical Informatics' WHERE code = 'MDI';
UPDATE subjects SET name ='Medieval Studies' WHERE code = 'MST';
UPDATE subjects SET name ='Microbiology' WHERE code = 'MIC';
UPDATE subjects SET name ='Microbiology (Graduate Group)' WHERE code = 'MIB';
UPDATE subjects SET name ='Middle East/South Asian Std' WHERE code = 'MSA';
UPDATE subjects SET name ='Military Science' WHERE code = 'MSC';
UPDATE subjects SET name ='Molecular and Cellular Biology' WHERE code = 'MCB';
UPDATE subjects SET name ='Molecular, Cell & Int Physio' WHERE code = 'MCP';
UPDATE subjects SET name ='Music' WHERE code = 'MUS';
UPDATE subjects SET name ='Native American Studies' WHERE code = 'NAS';
UPDATE subjects SET name ='Nature and Culture' WHERE code = 'NAC';
UPDATE subjects SET name ='Nematology' WHERE code = 'NEM';
UPDATE subjects SET name ='Neurobiology, Physio & Behavior' WHERE code = 'NPB';
UPDATE subjects SET name ='Neuroscience (Graduate Group)' WHERE code = 'NSC';
UPDATE subjects SET name ='Nursing' WHERE code = 'NRS';
UPDATE subjects SET name ='Nutrition' WHERE code = 'NUT';
UPDATE subjects SET name ='Nutrition Graduate Group' WHERE code = 'NGG';
UPDATE subjects SET name ='Nutritional Biology (Grad Grp)' WHERE code = 'NUB';
UPDATE subjects SET name ='Performance Studies (Grad Grp)' WHERE code = 'PFS';
UPDATE subjects SET name ='Pharmacology-Toxicology (Grad)' WHERE code = 'PTX';
UPDATE subjects SET name ='Philosophy' WHERE code = 'PHI';
UPDATE subjects SET name ='Physical Education' WHERE code = 'PHE';
UPDATE subjects SET name ='Physician Assistant Studies' WHERE code = 'PAS';
UPDATE subjects SET name ='Physics' WHERE code = 'PHY';
UPDATE subjects SET name ='Physiology Graduate Group' WHERE code = 'PGG';
UPDATE subjects SET name ='Plant Biology' WHERE code = 'PLB';
UPDATE subjects SET name ='Plant Biology (Graduate Group)' WHERE code = 'PBI';
UPDATE subjects SET name ='Plant Pathology' WHERE code = 'PLP';
UPDATE subjects SET name ='Plant Protection & Pest Mangmt' WHERE code = 'PPP';
UPDATE subjects SET name ='Plant Science' WHERE code = 'PLS';
UPDATE subjects SET name ='Political Science' WHERE code = 'POL';
UPDATE subjects SET name ='Pomology' WHERE code = 'POM';
UPDATE subjects SET name ='Population Biology' WHERE code = 'PBG';
UPDATE subjects SET name ='Portuguese' WHERE code = 'POR';
UPDATE subjects SET name ='Professional Accountancy' WHERE code = 'ACC';
UPDATE subjects SET name ='Psychology' WHERE code = 'PSC';
UPDATE subjects SET name ='Range Science' WHERE code = 'RMT';
UPDATE subjects SET name ='Religious Studies' WHERE code = 'RST';
UPDATE subjects SET name ='Russian' WHERE code = 'RUS';
UPDATE subjects SET name ='School of Veterinary Medicine' WHERE code = 'VET';
UPDATE subjects SET name ='Science & Technology Studies' WHERE code = 'STS';
UPDATE subjects SET name ='Science and Society' WHERE code = 'SAS';
UPDATE subjects SET name ='Short-Term Abroad Program' WHERE code = 'STP';
UPDATE subjects SET name ='Social Theory & Compar History' WHERE code = 'STH';
UPDATE subjects SET name ='Sociology' WHERE code = 'SOC';
UPDATE subjects SET name ='Soil Science' WHERE code = 'SSC';
UPDATE subjects SET name ='Spanish' WHERE code = 'SPA';
UPDATE subjects SET name ='Statistics' WHERE code = 'STA';
UPDATE subjects SET name ='Study of Religion' WHERE code = 'REL';
UPDATE subjects SET name ='Sustainable Ag & Food Sys' WHERE code = 'SAF';
UPDATE subjects SET name ='Technocultural Studies' WHERE code = 'TCS';
UPDATE subjects SET name ='Textiles & Clothing' WHERE code = 'TXC';
UPDATE subjects SET name ='Transportation Tech & Policy' WHERE code = 'TTP';
UPDATE subjects SET name ='Turkish' WHERE code = 'TSK';
UPDATE subjects SET name ='University Writing Program' WHERE code = 'UWP';
UPDATE subjects SET name ='Urdu' WHERE code = 'URD';
UPDATE subjects SET name ='Vegetable Crops' WHERE code = 'VCR';
UPDATE subjects SET name ='Veterinary Clinical Rotation' WHERE code = 'DVM';
UPDATE subjects SET name ='Veterinary Medicine' WHERE code = 'VMD';
UPDATE subjects SET name ='Viticulture & Enology' WHERE code = 'VEN';
UPDATE subjects SET name ='VM Anatomy, Physiol & Cell Bio' WHERE code = 'APC';
UPDATE subjects SET name ='VM Medicine and Epidemiology' WHERE code = 'VME';
UPDATE subjects SET name ='VM Molecular Biosciences' WHERE code = 'VMB';
UPDATE subjects SET name ='VM Pathology, Microbiol &Immun' WHERE code = 'PMI';
UPDATE subjects SET name ='VM Population Health & Reprod' WHERE code = 'PHR';
UPDATE subjects SET name ='VM Preventive Veterinary Med' WHERE code = 'MPM';
UPDATE subjects SET name ='VM Surgical & Radiological Sci' WHERE code = 'VSR';
UPDATE subjects SET name ='Wildlife, Fish & Conserv Biol' WHERE code = 'WFC';
UPDATE subjects SET name = 'Women''s Studies' WHERE code = 'WMS';
UPDATE subjects SET name ='Workload' WHERE code = 'WLD'
