from . import schedule
from . import feed
from . import profile
from . import uni_profile
from . import question
from . import admin
from . import api
from . import course
from . import notifications
from . import user
from . import auth
from . import onboard
from . import index
from . import unsubscribe
